In [1]:
import numpy as np
value=np.arange(50,100,5)
array1=value.reshape(5,2)
array2=array1 .reshape(10,1)
print(array2)



[[50]
 [55]
 [60]
 [65]
 [70]
 [75]
 [80]
 [85]
 [90]
 [95]]


In [66]:
import numpy as np
from scipy import stats

array=np.random.randint(1,101,size=100)
minimum=np.min(array)
maximum=np.max(array)
mean=np.mean(array)
median=np.median(array)
std_dev=np.std(array)
unique_values,counts=np.unique(array,return_counts=True)
num_unique=len(unique_values)
most_frequent_values=unique_values[np.argmax(counts)]
count_of_unique_values = dict(zip(unique_values,counts))

print("array=",array)
print("minimum=",minimum)
print("maximum=",maximum)
print("mean=",mean)
print("median=",median)
print("standerd derivation=",std_dev)
print("no. of unique values=",num_unique)
print("count of unique values=",count_of_unique_values)
print("most frequent value=",most_frequent_values)




array= [ 71  20  77  35  48  62  60  66  57  17  91  77  39  78  73  78  96  94
  55  44  94  27  28  74  90  45  98  82   9  78   2  10  85  80  14   5
  95  11  31  50   4  47  43  91  32  88  94  77  78  12  75  75  55  73
   7  71  64   8  14  69  31  41  99  28  55  44  99  19  56  44  68  73
   6  72  74  26  94  43  10  52  14  14  52  24  12  52  34   3  72  10
  17  40  37   9 100  21  73  33   8  84]
minimum= 2
maximum= 100
mean= 50.66
median= 52.0
standerd derivation= 29.88050200381513
no. of unique values= 65
count of unique values= {2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 2, 9: 2, 10: 3, 11: 1, 12: 2, 14: 4, 17: 2, 19: 1, 20: 1, 21: 1, 24: 1, 26: 1, 27: 1, 28: 2, 31: 2, 32: 1, 33: 1, 34: 1, 35: 1, 37: 1, 39: 1, 40: 1, 41: 1, 43: 2, 44: 3, 45: 1, 47: 1, 48: 1, 50: 1, 52: 3, 55: 3, 56: 1, 57: 1, 60: 1, 62: 1, 64: 1, 66: 1, 68: 1, 69: 1, 71: 2, 72: 2, 73: 4, 74: 2, 75: 2, 77: 3, 78: 4, 80: 1, 82: 1, 84: 1, 85: 1, 88: 1, 90: 1, 91: 2, 94: 4, 95: 1, 96: 1, 98: 1, 99: 2, 100: 1}


In [76]:
import numpy as np
matrix=np.identity(5)*5
print(matrix)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [116]:
import numpy as np
heights=np.array([165, 170, 175, 168, 172, 180, 160, 169, 176, 171, 174, 182, 158, 167, 173, 179, 163, 166, 177, 181])
weights=np.array([60, 65, 70, 75, 80, 85, 55, 58, 63, 68, 72, 77, 50, 62, 67, 74, 52, 57, 69, 73])
print("heights (cm):",heights)
print("weights (cm):",weights)

combined=np.column_stack((heights,weights))
print("combination=",combined)

mean_height=np.mean(heights)
mean_weight=np.mean(weights)
print("mean height:",mean_height)
print("mean weight:",mean_weight)

index_shortest=np.argmin(heights)
index_tallest=np.argmax(heights)
print("index of shortest individual=",index_shortest)
print("index of tallest individual=",index_tallest)

sorted_combined=combined[combined[:,0].argsort()]
print("sorted array based on height:",sorted_combined)

swapped_combined=combined[:,[1,0]]
print("array with swapped columns:",swapped_combined)

under_70kg = combined[combined[:,1]<70]
print("individuals with weight below 70kg:",under_70kg)

heights (cm): [165 170 175 168 172 180 160 169 176 171 174 182 158 167 173 179 163 166
 177 181]
weights (cm): [60 65 70 75 80 85 55 58 63 68 72 77 50 62 67 74 52 57 69 73]
combination= [[165  60]
 [170  65]
 [175  70]
 [168  75]
 [172  80]
 [180  85]
 [160  55]
 [169  58]
 [176  63]
 [171  68]
 [174  72]
 [182  77]
 [158  50]
 [167  62]
 [173  67]
 [179  74]
 [163  52]
 [166  57]
 [177  69]
 [181  73]]
mean height: 171.3
mean weight: 66.6
index of shortest individual= 12
index of tallest individual= 11
sorted array based on height: [[158  50]
 [160  55]
 [163  52]
 [165  60]
 [166  57]
 [167  62]
 [168  75]
 [169  58]
 [170  65]
 [171  68]
 [172  80]
 [173  67]
 [174  72]
 [175  70]
 [176  63]
 [177  69]
 [179  74]
 [180  85]
 [181  73]
 [182  77]]
array with swapped columns: [[ 60 165]
 [ 65 170]
 [ 70 175]
 [ 75 168]
 [ 80 172]
 [ 85 180]
 [ 55 160]
 [ 58 169]
 [ 63 176]
 [ 68 171]
 [ 72 174]
 [ 77 182]
 [ 50 158]
 [ 62 167]
 [ 67 173]
 [ 74 179]
 [ 52 163]
 [ 57 166]
 [ 69 177]
 [ 